### 获取当前用户余额信息
GET http://127.0.0.1:9001/imooc/ecommerce-account-service/balance/current-balance
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImhlZG9uXCJ9IiwianRpIjoiYTllOTJmNzgtOWFlNC00MWJmLTkzNzItMTQ5ZjVmZThkYzNhIiwiZXhwIjoxNjU0MDk5MjAwfQ.GhzJbQZrdV9JMNc9f8uhgkx5EnZSfF4wFkyJ5bHKOTL-OfIhedDkFaXZeEo4xaqHIgGELjdIQiMqNHNmBypFKrpNL3mQOaeEKHgh3Wt3Noul-4IMXzJTMU7i1PfDYxCBd3C8MYre2H9b1kg0B1GQed12NNBCR1vtiZaqoklBd2AkciyjHU-oR3NdrCRzkBoRbOgJIYhrl9RTtxTjQp96ZW_9LI0bQUg83777YJnxXjnOAWKn1lXFiGAHuMF2pAQNkYxf_Enfpg5a3kaqPLCQgFRiAcc7lCkgfOG-C8Py8RI4WoNXcOfe10KYrL3tQ4uvkfio5ywTyKo00_pWdfAgFA
### 扣减用户余额
PUT http://127.0.0.1:9001/imooc/ecommerce-account-service/balance/deduct-balance
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImhlZG9uXCJ9IiwianRpIjoiYTllOTJmNzgtOWFlNC00MWJmLTkzNzItMTQ5ZjVmZThkYzNhIiwiZXhwIjoxNjU0MDk5MjAwfQ.GhzJbQZrdV9JMNc9f8uhgkx5EnZSfF4wFkyJ5bHKOTL-OfIhedDkFaXZeEo4xaqHIgGELjdIQiMqNHNmBypFKrpNL3mQOaeEKHgh3Wt3Noul-4IMXzJTMU7i1PfDYxCBd3C8MYre2H9b1kg0B1GQed12NNBCR1vtiZaqoklBd2AkciyjHU-oR3NdrCRzkBoRbOgJIYhrl9RTtxTjQp96ZW_9LI0bQUg83777YJnxXjnOAWKn1lXFiGAHuMF2pAQNkYxf_Enfpg5a3kaqPLCQgFRiAcc7lCkgfOG-C8Py8RI4WoNXcOfe10KYrL3tQ4uvkfio5ywTyKo00_pWdfAgFA

{
  "userId": 10,
  "balance": 2000
}
