### 查询服务
GET http://127.0.0.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImhlZG9uXCJ9IiwianRpIjoiY2RlNTUzNWMtMTYzMi00ZWZkLTgyNzYtZTRmYTk5Yzk5ODQ1IiwiZXhwIjoxNjUzODQwMDAwfQ.dxSEU2PPn-sv0HWPwQysj-Q5nBUrzyFxOwGEof0ORVTgiJ6oI3N6YppMqhz9w53tJ_sr-6bd8kTXFDbLrG5fyp7Ac0NMqL5sK6Ia9fQhsvmaw1ayeKNXIqgsHcb3wrm8AAe5DbprweGe5HfCq0F5Tx_IbUDbK1NVEwXivuUEH9s_xTTzRID2bDPWbd8PlIWYzjdAbWblofZIJnFAtikGpJ1IjDKZhMPQyQ-o89eRWcjzYbDWwGrS7M54pse7KQvOP5FSGg09G4J0QXU7g-YQaXyVbWjiio6B6atyRZXRdb4tvl1okttEJHWiGl071SYpGJs6Ky3FfAn6BSIhGlcLKg
token: imooc