### 查询服务
GET http://127.0.0.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEyLFwidXNlcm5hbWVcIjpcImhlZG9uLTJcIn0iLCJqdGkiOiI5MDc4Mjg0OC03ZThkLTRiNjUtYjMxNy1lNDU2MDlhZDJjYzkiLCJleHAiOjE2NTM2NjcyMDB9.PGenAJGqGgTA5vi3ejpUch9K9yVStA8_UhlMxZVjlZ5Ob8E6w4VR4mhPRBogzwMSnRkcdhwU7-JRTRW3-P9izis1zC0dSb19VSKqjrgKRZqB0xmiIwyy8W-0qXdyL2vQ3sw89AVphYcLxaFhq0obXxUv9S4gOLYbiWGkq4qwzIy-mtykQNyxxi7cYr01BBvTcrsMomhje1ymU4EEV1pDqn8IQDcYi2ZiFvouXGpRsvWlJr5dExHxTg0MZdrsIOjCzC0dHvWj1b-GarSm2cH1YIBQIH4yQjUKL68rsY9iDTTzZhWP4muxXewi7ea4lspeUL5UYQYtawS9YBl8a1Wnlg
token: imooc